# GitHub Actions workflow that includes cost estimation
name: Infrastructure Deployment
on:
  pull_request:
    paths: [ 'terraform/**' ]

jobs:
  cost-estimate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Generate cost estimate
      run: |
        cd terraform
        infracost breakdown --path . --format json --out-file /tmp/infracost.json

    - name: Check cost increase
      run: |
        # Fail if monthly cost increase exceeds $500
        COST_INCREASE=$(jq -r '.diffTotalMonthlyCost' /tmp/infracost.json)
        if (( $(echo "$COST_INCREASE > 500" | bc -l) )); then
          echo "Cost increase of $COST_INCREASE exceeds threshold"
          exit 1
        fi

    - name: Post cost comment
      uses: infracost/actions/comment@v1
      with:
        path: /tmp/infracost.json
        behavior: update
