# Development override for docker-compose
version: '3.8'

services:
  webapp:
    build:
      context: .
      target: development
    ports:
      - "3000:80"  # Different port for dev
    volumes:
      # Live reload for development
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NODE_ENV=development
      - DEBUG=true
    # Remove resource limits for development
    deploy:
      resources: {}

  # Optional: Add development tools
  # adminer:
  #   image: adminer
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - webapp_network
