variables:
  azureSubscription: "Azure subscription 1"
  location: "polandcentral"
  resourceGroup: "tfstate-rg" #located in polandcentral
  storageAccountName: "tfstatecriy"
  containerName: "terraformtfstate"
  terraform_version: 1.11.3
  backendServiceArm: "catherinevee_manid"

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: "sdfsfsa"
  jobs:
  - job: "inframap"
    steps:
    - task: GoTool@0
      inputs:
        version: '1.10'
    - task: Bash@3
      inputs:
        script: |
          git clone https://github.com/cycloidio/inframap
          cd inframap
          go mod download
          make build
          inframap
      displayName: 'Run a multi-line script'
