- name: "Assign Syslog Servers for Cisco iOS"
  hosts: cisco
  connection: network_cli

  tasks:
  - name: "Send Syslog Commands"
    cisco.ios.ios_logging_global:
      config:
        hosts:
        - hostname: " {{ item.ip }} "
          transport:
            tcp:
              port: "{{ item.port }}"
      stage: replaced
    loop: " {{syslog. hosts }} "
    when: item.port is defined
    register: logging_output

  - name: "Print Output"
    debug:
      msg: "{{ item. commands }}"
    loop: "{{ logging_output.results }}"
    loop control:
      label: none
    when: item.commands is defined
