---

- name: "NAPALM Getter"
  hosts: all
  connection: network_cli

  tasks:
  - name: "Get NAPALM facts"
    napalm_get_facts:
      hostname: " {{ inventory_hostname }}"
      username: " {{ ansible_user }}"
      password: " {{ ansible_password }}"
      dev_os: "{{napalm_platform}}"
      filter: "[interfaces_ip, mac_address_table]"
    register: result
  - name: "Print Result"
    debug:
      msg: "{{result}}"
