---

- name: "Configure Login Banners on VyOS"
  hosts: vyos
  connection: network_cli

  tasks:
  - name: "banner"
    vyos.vyos.vyos_banner:
      banner: pre-login
      state: present
      text: "UNAUTHORIZED ACCESS IS PROHIBITED"

  - name: "banner"
    vyos.vyos.vyos_banner:
      banner: post-login
      state: absent
      text: "LOGOUT"
