---

- name: "Configure MOTD Banner for IOS"
  hosts: cisco-switch
  gather_facts: false
  connection: network_cli
  
  tasks:
    - name: "Configure MOTD Banner"
      cisco.ios.ios_banner:
        banner: motd
        text: |
          MOTD
        state: present
      
      register: motd_banner

    - debug: var=motd_banner
        