# ingress.yaml
#
# This file defines the Kubernetes Ingress resource for external access to the dorm website.
# Ingress manages external access to the services in a cluster, typically HTTP.
{{- if .Values.ingress.enabled -}} # Only create Ingress if enabled in values.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "catherine.starrez.com.fullname" . }} # Full name for the Ingress.
  labels:
    {{- include "catherine.starrez.com.labels" . | nindent 4 }} # Common labels.
  annotations:
    # Recommended annotation for Nginx Ingress Controller to rewrite paths.
    # Adjust based on your Ingress Controller.
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Annotation for cert-manager to automatically issue/renew TLS certificates.
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Replace with your ClusterIssuer name.
    {{- end }}
    # Add any other Ingress-specific annotations here.
spec:
  ingressClassName: {{ .Values.ingress.className }} # Specifies the Ingress controller to use.
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }} # Hostname for which the Ingress rule applies.
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }} # Path for the Ingress rule.
            pathType: {{ .pathType }} # Path matching type.
            backend:
              service:
                name: {{ include "catherine.starrez.com.fullname" $ }} # Name of the target service.
                port:
                  number: {{ $.Values.service.port }} # Port of the target service.
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }} # Hosts for which TLS certificates will be managed.
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }} # Name of the Secret holding TLS certificates.
  {{- end }}
{{- end }}