apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-west-2
  version: "1.28"

managedNodeGroups:
- name: managed-ng-1
  instanceType: t3.medium
  minSize: 1
  maxSize: 10
  desiredCapacity: 3
  volumeSize: 20
  ssh:
    allow: true # Enable SSH access
  labels: {role: worker}
  tags:
    nodegroup-role: worker
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoScaler: true
      externalDNS: true
      certManager: true
      ebs: true
      efs: true
      awsLoadBalancerController: true

# VPC Configuration
vpc:
  subnets:
    private:
      us-west-2a: { id: subnet-12345 }  
      us-west-2b: { id: subnet-67890 }
    public:
      us-west-2a: { id: subnet-abcde }
      us-west-2b: { id: subnet-fghij }
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true


# Add-ons
addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest
  wellKnownPolicies:
    ebsCSIController: true