# Network ACL
  productionNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref productionVPC
      Tags:
        - Key: "Name"
          Value: "productionNetworkAcl"

  # Network ACL Inbound Rules (allowing HTTP, HTTPS, and SSH)
  productionNetworkAclInbound:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref productionNetworkAcl
      RuleNumber: 100
      Protocol: "6" # TCP
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: "0.0.0.0/0"
      PortRange:
        From: 22  # SSH
        To: 22
      Ipv6CidrBlock: "0::/0"
      RuleAction: "allow"
  
  productionNetworkAclInboundHttp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref productionNetworkAcl
      RuleNumber: 101
      Protocol: "6" # TCP
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: "0.0.0.0/0"
      PortRange:
        From: 80  # HTTP
        To: 80

  productionNetworkAclInboundHttps:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref productionNetworkAcl
      RuleNumber: 102
      Protocol: "6" # TCP
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: "0.0.0.0/0"
      PortRange:
        From: 443  # HTTPS
        To: 443

  # Network ACL Outbound Rules (allowing all outbound traffic)
  productionNetworkAclOutbound:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref productionNetworkAcl
      RuleNumber: 100
      Protocol: "-1" # All protocols
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: "0.0.0.0/0"
      PortRange:
        From: 0
        To: 65535

  # Network ACL Association with the Public Subnet
  productionNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref productionPublicSubnet
      NetworkAclId: !Ref productionNetworkAcl

Outputs:
  VPCId:
    Description: "VPC ID"
    Value: !Ref productionVPC

  SubnetId:
    Description: "Public Subnet ID"
    Value: !Ref productionPublicSubnet

  InternetGatewayId:
    Description: "Internet Gateway ID"
    Value: !Ref productionInternetGateway

  NetworkAclId:
    Description: "Network ACL ID"
    Value: !Ref productionNetworkAcl