variables:
  storageAccountName: "tfstatesa"
  containerName: "tfstate-container"
  terraform_version: 1.11.3
  resourceGroup: "polandcentralrg-1"
  backendServiceArm: "catherinevee_manid"
  backendAzureRmResourceGroupName: $(resourceGroup)
  backendAzureRmStorageAccountName: $(storageAccountName)
  backendAzureRmContainerName: $(containerName)
  backendAzureRmKey: "terraform.tfstate"
 

trigger:
- main
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r) 
pr: none


stages :  
  - stage: terraform_plan_apply
    jobs:
      - job: terraform_apply
        steps:
          - task: TerraformInstaller@2
            inputs:
              terraformVersion: '$(terraform_version)
          - task: TerraformCLI@2
            inputs:
              command: 'init'
              backendType: 'azurerm'
              backendServiceArm: 'catherinevee_manid'
              backendAzureRmResourceGroupName: 'polandcentralrg-1'
              backendAzureRmStorageAccountName: 'tfstate-sa'
              backendAzureRmContainerName: 'tfstate-container'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: true