variables:
  azureSubscription: "Azure subscription 1"
  resourceGroup: "tfstate-rg" #located in polandcentral
  storageAccountName: "tfstatecriy"
  containerName: "terraformtfstate"
  terraform_version: 1.11.3

  backendServiceArm: "catherinevee_manid"
  backendAzureRmResourceGroupName: $(resourceGroup)
  backendAzureRmStorageAccountName: $(storageAccountName)
  backendAzureRmContainerName: $(containerName)
  backendAzureRmKey: "terraform.tfstate"
 

trigger:
- main
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r) 
pr: none


stages :  
  - stage: terraform_plan_apply
    jobs:
      - job: terraform_apply
        steps:
        - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
          inputs:
            terraformVersion: '$(terraform_version)'
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'catherinevee_manid'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Set Azure Subscription
              az account set -s $(azureSubscription)
              
              # Create resource group
              az group create -l polandcentral -n $(resourceGroup)
              
              # Create storage account
              az storage account create -n $(storageAccountName) -g $(resourceGroup) -l polandcentral --sku Standard_LRS --kind StorageV2
              
              # Create blob container
              az storage container create --account-name $(storageAccountName) --name $(containerName) 