variables:
  storageAccountName: "tfstatesa"
  containerName: "tfstate-container"
  terraform_version: 1.11.3
  resourceGroup: "polandcentralrg-1"
  backendServiceArm: "catherinevee_manid"
  backendAzureRmResourceGroupName: $(resourceGroup)
  backendAzureRmStorageAccountName: $(storageAccountName)
  backendAzureRmContainerName: $(containerName)
  backendAzureRmKey: "terraform.tfstate"
 

trigger:
- main
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r) 
pr: none


stages :  
  - stage: terraform_plan_apply
    jobs:
      - job: terraform_apply
        steps:
        - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
          inputs:
            terraformVersion: '$(terraform_version)'
        - task: TerraformTaskV4@4
          displayName: Initialize Terraform
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'catherinevee_manid'
            backendAzureRmResourceGroupName: 'polandcentralrg-1'
            backendAzureRmStorageAccountName: 'tfstatecriy'
            backendAzureRmContainerName: 'tfstate-container'
            backendAzureRmKey: 'state.tfstate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'