variables:
  azureSubscription: "Azure subscription 1"
  location: "polandcentral"
  resourceGroup: "tfstate-rg" #located in polandcentral
  storageAccountName: "tfstatecriy"
  containerName: "terraformtfstate"
  terraform_version: 1.11.3
  backendServiceArm: "catherinevee_manid"
  backendServiceResourceGroup: "polandcentralrg-1" #the RG of the Managed Identity

trigger:
- main
name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
pr: none

stages:
- stage: "Generate_Storage_Account"
  jobs:
  - job: "terraform_install"
    steps:
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: "terraform install"
      inputs:
        terraformVersion: '$(terraform_version)'
  - job: "azure_cli_job"
    steps:
    - task: AzureCLI@2
      name: "azurecli"
      displayName: "Generate Storage Account"
      inputs:
        azureSubscription: 'catherinevee_manid'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Set Azure Subscription
          az account set -s $(azureSubscription)

          # Create resource group
          az group create -l $(location) -n $(resourceGroup)

          # Create storage account
          az storage account create -n $(storageAccountName) -g $(resourceGroup) -l $(location) --sku Standard_LRS --kind StorageV2

          # Create blob container
          az storage container create --account-name $(storageAccountName) --name $(containerName)

          storageAccountResourceID=$(az storage account show --resource-group $(resourceGroup) --name $(storageAccountName) --query "[id][0]")
          echo "##vso[task.setvariable variable=sari;isOutput=true ]$storageAccountResourceID" 
          echo "11111"
          echo "terraform import azurerm_resource_group.polandcentralrg-1 $storageAccountResourceID" >> terraformimport.txt
          cat terraformimport.txt
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'

    - task: TerraformCLI@2
      inputs:
        command: 'import'
        resourceAddress: $backendServiceResourceGroup
        resourceId: $storageAccountResourceID
