apiVersion: v1
kind: Config
clusters:
- name: production
  cluster:
    server: https://production.cathy09623511.com
    certificate-authority: /certs/production-ca.crt
- name: development
  cluster:
    server: https://development.cathy09623511.com
    certificate-authority: /certs/development-ca.crt
- name: test
  cluster:
    server: https://test.cathy09623511.com
    certificate-authority: /certs/test-ca.crt
contexts:
- name: production
  context:
    cluster: production
    user: prod-user
- name: development
  context:
    cluster: development
    user: dev-user
- name: test
  context:
    cluster: test
    user: test-user
current-context: development
users:
- name: prod-user
  user:
    client-certificate: certs/prod-user.crt
    client-key: certs/prod-user.key
- name: dev-user
  user:
    client-certificate: certs/dev-user.crt
    client-key: certs/dev-user.key
- name: test-user
  user:
    client-certificate: certs/test-user.crt
    client-key: certs/test-user.key
- name: test-principal
  user:
    token: ${{secrets.testkubetoken}}
- name: prod-principal
  user:
    token: ${{secrets.prodkubetoken}}
