apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: init-service
    image: alpine:3.14
    command: [ 'sh', '-c', 'until nslookup database; do echo waiting for database; sleep 2; done;' ]

  containers:
  - name: app
    image: nginx:1.21
