apiVersion: v1
kind: LimitRange
metadata:
  name: production-cpu-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    mix:
      cpu: 100m
    type: Container
