apiVersion: v1
kind: Pod
metadata:
  name: test-ephemeral
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /test
      name: ephemeral-volume
  volumes:
  - name: ephemeral-volume
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: ephemeral
        spec:
          accessModes: [ 'ReadWriteOnce' ]
          storageClassName: 'fast-storage'
          resources:
            requests:
              storage: 1Gi
