---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: amazonbsio1
provisioner: Kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "30"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
