apiVersion: v1
kind: PersistentVolume
metadata:
  name: prodVolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: "a332kfis9ks938401kd"
    fsType: ext4
