replicaCount: 3

image:
  repository: catherinevee/catherinevee
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: http

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: catherine.it.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: housing-tls-secret
    hosts:
    - catherine.it.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment-specific configurations
environments:
  development:
    replicaCount: 1
    ingress:
      hosts:
      - host: dev.catherine.it.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: housing-dev-tls-secret
        hosts:
        - dev.catherine.it.com
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    autoscaling:
      enabled: false

  staging:
    replicaCount: 2
    ingress:
      hosts:
      - host: staging.catherine.it.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: housing-staging-tls-secret
        hosts:
        - staging.catherine.it.com
    autoscaling:
      minReplicas: 2
      maxReplicas: 6

  production:
    replicaCount: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 15
      targetCPUUtilizationPercentage: 60

# Application configuration
config:
  nginx:
    host: catherine.it.com
    port: "8080"
    workerProcesses: "auto"
    workerConnections: "1024"
  app:
    env: production
    logLevel: info

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

# Network policies
networkPolicy:
  enabled: false
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 25%

  # Health checks
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
