replicaCount: 1

image:
  tag: "dev"

config:
  nginx:
    host: dev.catherine.it.com
  app:
    env: development
    logLevel: debug

ingress:
  hosts:
  - host: dev.catherine.it.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: housing-dev-tls-secret
    hosts:
    - dev.catherine.it.com

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false
