on:
  workflow_dispatch:
  push:


permissions:
  id-token: write

jobs:
  cloudformationdeployment:
    runs-on: ubuntu-latest
    steps:
    - name: "Authenticate to AWS via OIDC"
      uses: actions/checkout@v2.4.0
      with:
        role-to-assume: arn:aws:iam::025066254478:oidc-provider/token.actions.githubusercontent.com
        aws-region: us-west-2
    - run: |
        Install-Module -Name AWS.Tools.EC2 -Force
        Get-EC2VPC
      shell: pwsh
    - name: "Install AWS SDK for PowerShell"
      shell: pwsh
      run: Install-Module -Name AWS.Tools.CloudFormation -Force
