name: Monitored Production Workflow

on:
  push:
    branches: [main]
  schedule:
    # Run health check daily at 9 AM UTC
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Track workflow execution time
      - name: Record start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Your deployment steps here
          sleep 30  # Simulate deployment time

      # Calculate and report execution time
      - name: Report execution metrics
        if: always()
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))

          echo "Workflow execution time: ${DURATION} seconds"

          # Send metrics to monitoring system
          curl -X POST "${{ secrets.METRICS_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"workflow\": \"${{ github.workflow }}\",
              \"job\": \"${{ github.job }}\",
              \"duration\": $DURATION,
              \"status\": \"${{ job.status }}\",
              \"repository\": \"${{ github.repository }}\",
              \"branch\": \"${{ github.ref_name }}\",
              \"commit\": \"${{ github.sha }}\",
              \"run_id\": \"${{ github.run_id }}\"
            }" || echo "Failed to send metrics"

      # Send alerts on failure
      - name: Send failure alert
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST "$SLACK_WEBHOOK" \
            -H 'Content-type: application/json' \
            --data "{
              \"text\": \"🚨 Deployment failed in ${{ github.repository }}\",
              \"attachments\": [{
                \"color\": \"danger\",
                \"fields\": [
                  {\"title\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"short\": true},
                  {\"title\": \"Commit\", \"value\": \"${{ github.sha }}\", \"short\": true},
                  {\"title\": \"Run\", \"value\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \"short\": false}
                ]
              }]
            }"

      # Send success notification for main branch deployments
      - name: Send success notification
        if: success() && github.ref == 'refs/heads/main'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST "$SLACK_WEBHOOK" \
            -H 'Content-type: application/json' \
            --data "{
              \"text\": \"✅ Deployment successful for ${{ github.repository }}\",
              \"attachments\": [{
                \"color\": \"good\",
                \"fields\": [
                  {\"title\": \"Commit\", \"value\": \"${{ github.sha }}\", \"short\": true},
                  {\"title\": \"Duration\", \"value\": \"${DURATION}s\", \"short\": true}
                ]
              }]
            }"
