name: Secure Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Use environment protection

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/

      - name: Deploy to AWS
        env:
          # Access secrets through the secrets context
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Combine secrets with public configuration
          AWS_REGION: us-east-1
          S3_BUCKET: my-app-production
        run: |
          echo "Deploying to AWS S3..."
          echo "Region: $AWS_REGION"
          echo "Bucket: $S3_BUCKET"

          # Configure AWS CLI with credentials
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

          # Sync files to S3
          aws s3 sync dist/ s3://$S3_BUCKET/ --delete

          # Invalidate CloudFront cache
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Update database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Running database migrations..."
          # Use the database connection securely
          # Never echo the DATABASE_URL directly
          echo "Database connection configured"

          # Run migrations (example)
          # npx prisma migrate deploy

      - name: Send deployment notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST "$SLACK_WEBHOOK_URL" \
            -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ Production deployment completed for commit ${{ github.sha }}\"}"
