name: Build and Push Docker Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t starrez:${{ github.sha }} .
      - name: Run Tests
        run: docker run --rm starrez:${{ github.sha }} npm test
      - name: Push to Registry
        run: |
          docker tag starrez:${{ github.sha }} catherinevee/catherinevee/starrez:${{ github.sha }}
          docker tag starrez:${{ github.sha }} catherinevee/catherinevee/starrez:latest
          docker push catherinevee/catherinevee/starrez:${{ github.sha }}
          docker push catherinevee/catherinevee/starrez:latest
