name: Python Application

on: [push, pull_request]

jobs:
 test:
  runs-on: ubuntu-latest

  # Test against multiple Node.js versions
  strategy:
    matrix:
      node-version: [16, 18, 20]

  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
