# GitHub Actions workflow
name: Secure Kubernetes Deployment

on:
  push:
    branches: [ main ]

jobs:
  scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Verify commit signature
      run: git verify-commit HEAD

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY }}/app:${{ github.sha }}

    - name: Scan image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.REGISTRY }}/app:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        severity: 'CRITICAL'

    - name: Deploy to Kubernetes
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/deployment.yaml
          kubernetes/service.yaml
        images: |
          ${{ secrets.REGISTRY }}/app:${{ github.sha }}
        namespace: production
