name: Secure Workflow Triggers

# Be explicit about which events trigger workflows
on:
  push:
    branches: [main, develop]
    # Never trigger on all branches - limit scope
  pull_request:
    branches: [main]
    # Use pull_request_target carefully - it has access to secrets

  # For workflows that use pull_request_target, add safety checks
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]

jobs:
  # Security gate for external contributions
  security-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'

    steps:
      # Only checkout the base branch initially, not the PR code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      # Verify the PR is from a trusted source
      - name: Check PR source
        run: |
          # Check if PR is from a fork
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "PR is from external fork: ${{ github.event.pull_request.head.repo.full_name }}"
            
            # Check if author is a collaborator
            AUTHOR="${{ github.event.pull_request.user.login }}"
            if gh api repos/${{ github.repository }}/collaborators/$AUTHOR >/dev/null 2>&1; then
              echo "✅ Author is a repository collaborator"
            else
              echo "❌ Author is not a collaborator, manual review required"
              exit 1
            fi
          else
            echo "✅ PR is from the same repository"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only after verification, checkout the PR code
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Scan for suspicious changes in workflow files
      - name: Scan workflow changes
        run: |
          # Check if .github/workflows was modified
          if git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -q "^\.github/workflows/"; then
            echo "⚠️ Workflow files modified in this PR"
            echo "Modified workflow files:"
            git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep "^\.github/workflows/"
            
            # Require manual approval for workflow changes from forks
            if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
              echo "❌ External contributors cannot modify workflows without manual review"
              exit 1
            fi
          fi
