name: Sync Github Repo to AzureDevOps Repo
on:
  push:
    branches:
      - 'main' # applies for all branches in github.
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZ_USERNAME: ${{secrets.AZ_USERNAME}} # calling secrets from environment variables
        AZ_PAT: ${{secrets.AZ_PAT}}
        AZ_USEREMAIL: ${{secrets.AZ_USEREMAIL}}
        AZ_ORG: ${{secrets.AZ_ORG}}
      run: |
         chmod +x ./commit.sh
         ./commit.sh
      shell: bash
  
