name: Sync Github Repo to AzureDevOps Repo
on:
  push:
    branches:
      - '*' # applies for all branches in github.
      - '!master' # This line is used to restrict this pipeline which won't triggers for master branch. remove this if you need to trigger for code push in master branch (Create PR if needed in devops repos)
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZ_USERNAME: ${{secrets.AZ_USERNAME}} # calling secrets from environment variables
        AZ_PAT: ${{secrets.AZ_PAT}}
        AZ_USEREMAIL: ${{secrets.AZ_USEREMAIL}}
        AZ_ORG: ${{secrets.AZ_ORG}}
      run: |
         chmod +x ./commit.sh
         ./commit.sh # it will calls 'commit.sh' file. Thats where our logic is in.
      shell: bash
  
